version: 2.0.{build}

assembly_info:
  patch: true
  file: CommonAssemblyInfo.cs
  assembly_version: "2.0.0.0"
  assembly_file_version: "{version}.0"
  assembly_informational_version: "{version}.0"

build:
  project: src\CSharp\MetadataWebApi\MetadataWebApi.msbuild
  verbosity: minimal

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off
